In [1]:
#Libraries

#Python Libs
import sys
import os
import glob
import traceback
from datetime import datetime
import time
from geopy import distance


#Data Analysis Libs
import pandas as pd
import numpy as np

In [2]:
#Functions
def select_input_files(enh_buste_base_path,init_date,fin_date,suffix):
        selected_files = []
        all_files = glob.glob(os.path.join(enh_buste_base_path,"*"))

        for file_ in all_files:
                try:
                        file_date = pd.to_datetime(file_.split('/')[-1],format=('%Y_%m_%d' + suffix  + '.csv'))
                        if (file_date >= init_date) and (file_date <= fin_date):
                                selected_files.append((file_,file_date))
                except:
                        continue

        return sorted(selected_files)

def get_gtfs_path(query_date):
    INTERMEDIATE_OTP_DATE = pd.to_datetime("2019-05-13", format="%Y-%m-%d")
    router_id = ''

    if (query_date <= INTERMEDIATE_OTP_DATE):
        return 'campina-gtfs-2019'
    else:
        return 'campina-gtfs-2017'

## Main

In [3]:
otp_suggestions_filepath = 'data/output/2019_05_13_bus_trips_otp_itineraries.csv'
bus_trips_folderpath = 'data/input'
gtfs_base_folderpath = 'data/input'
output_folderpath = 'data/output'

In [4]:
file_date_str = otp_suggestions_filepath.split('/')[-1].split('_bus_trips_')[0]
file_date = pd.to_datetime(file_date_str,format='%Y_%m_%d')
print "Processing File:", otp_suggestions_filepath

Processing File: data/output/2019_05_13_bus_trips_otp_itineraries.csv

In [5]:
    # Extracting itinerary part name for later use
    itinerary_part_name = otp_suggestions_filepath.split('/')[-1].split('_')[5]
    # Read OTP Suggestions
    otp_suggestions_raw = pd.read_csv(otp_suggestions_filepath, parse_dates=['date','otp_start_time','otp_end_time'])

    if len(otp_suggestions_raw) == 0:
        print "Zero OTP suggestions found."
        print "Skipping next steps..."
        exit(0)

In [6]:
def prepare_otp_data(otp_data):
        #Fixing prefix
        otp_data.columns = otp_data.columns.str.replace('otp_','')
        otp_data = otp_data.add_prefix('otp_')
        
        #Fixing Timezone difference - when needed
        otp_data['otp_start_time'] = otp_data['otp_start_time'] - pd.Timedelta('10800 s')
        otp_data['otp_end_time'] = otp_data['otp_end_time'] - pd.Timedelta('10800 s')
        
        #Adjusting route format to have 3 numbers
        otp_data['otp_route'] = otp_data['otp_route'].astype(str)
        otp_data['otp_route'] = np.where(otp_data['otp_mode'] == 'BUS',
                            otp_data['otp_route'].astype(str).str.replace("\.0",'').str.zfill(3),
                            otp_data['otp_route'])

        return otp_data

In [7]:
    # Prepare OTP data for analysis
    otp_suggestions = prepare_otp_data(otp_suggestions_raw)    
    
    # Read stops data
    stops_filepath = gtfs_base_folderpath + os.sep + get_gtfs_path(file_date) + os.sep + 'stops.txt'
    stops_df = pd.read_csv(stops_filepath)
    
    # Adding Parent Stop data to OTP Suggestions TODO
    stops_parent_stations = stops_df[['stop_id','parent_station']]
    otp_suggestions = otp_suggestions.merge(stops_parent_stations.add_prefix('from_'),
                                                left_on='otp_from_stop_id',
                                                right_on='from_stop_id',
                                                how='left') \
                                        .merge(stops_parent_stations.add_prefix('to_'),
                                                left_on='otp_to_stop_id',
                                                right_on='to_stop_id',
                                                how='left') \
                                        .drop(['from_stop_id','to_stop_id'], axis=1) \
                                        .rename(index=str, columns={'from_parent_station':'otp_from_parent_station',
                                                                    'to_parent_station':'otp_to_parent_station'})
        
    otp_suggestions_bus_legs = otp_suggestions[otp_suggestions['otp_mode'] == 'BUS']
    otp_suggestions_walk_legs = otp_suggestions[otp_suggestions['otp_mode'] == 'WALK']

In [8]:
otp_suggestions.head()

,otp_date,otp_user_trip_id,otp_itinerary_id,otp_leg_id,otp_start_time,otp_end_time,otp_mode,otp_route,otp_from_stop_id,otp_to_stop_id,otp_duration_mins,otp_from_parent_station,otp_to_parent_station
0,2019-05-13,491551.0,1,1,2019-05-13 05:13:45,2019-05-13 05:13:46,WALK,nan,NaN,NaN,0.016667,NaN,NaN
1,2019-05-13,491551.0,1,2,2019-05-13 05:13:47,2019-05-13 05:43:31,BUS,944,491551.0,386521.0,29.733333,NaN,NaN
2,2019-05-13,491551.0,1,3,2019-05-13 05:43:31,2019-05-13 05:47:06,WALK,nan,NaN,NaN,3.583333,NaN,NaN
3,2019-05-13,491551.0,1,4,2019-05-13 05:47:40,2019-05-13 05:56:33,BUS,903B,386641.0,386291.0,8.883333,NaN,NaN
4,2019-05-13,491551.0,1,5,2019-05-13 05:56:34,2019-05-13 05:56:35,WALK,nan,NaN,NaN,0.016667,NaN,NaN

## Read and Prepare Bus Trip Data

In [9]:
bus_trips_filepath = bus_trips_folderpath + os.sep + file_date_str + '_bus_trips.csv'
bus_trips = pd.read_csv(bus_trips_filepath, dtype={'route': object},parse_dates=['gps_datetime']) \
                                        .sort_values(['route','busCode','tripNum','gps_datetime']) \
                                        .assign(route = lambda x: x['route'].astype(str).str.replace("\.0",'').str.zfill(3))  \
                                        .drop_duplicates()

In [10]:
bus_trips.head()

,route,tripNum,shapeId,routeFrequency,shapeSequence,shapeLat,shapeLon,distanceTraveledShape,busCode,gpsPointId,gpsLat,gpsLon,distanceToShapePoint,gps_datetime,stopPointId,problem
5900,004A,1,90026,low_frequency,173,-7.23043,-35.87588,9535.0,3005,11553,-7.230581,-35.87565,30.42416,2019-05-13 06:45:24,385835,NO_PROBLEM
5962,004A,1,90026,low_frequency,45,-7.22907,-35.87689,3163.0,3005,11678,-7.228993,-35.87696,11.529692,2019-05-13 06:45:55,386394,NO_PROBLEM
6129,004A,1,90026,low_frequency,74,-7.22220,-35.87565,4030.0,3005,-,-,-,-,2019-05-13 06:47:47,386129,BETWEEN
6244,004A,1,90026,low_frequency,86,-7.21908,-35.87549,4429.0,3005,12300,-7.219028,-35.8755,5.8864255,2019-05-13 06:48:59,386131,NO_PROBLEM
6486,004A,1,90026,low_frequency,152,-7.22434,-35.87674,8788.0,3005,-,-,-,-,2019-05-13 06:51:35,385833,BETWEEN

In [24]:
bus_trips[bus_trips.route == "944"]

,route,tripNum,shapeId,routeFrequency,shapeSequence,shapeLat,shapeLon,distanceTraveledShape,busCode,gpsPointId,gpsLat,gpsLon,distanceToShapePoint,gps_datetime,stopPointId,problem
278,944,1,72976,high_frequency,81,-7.26725,-35.88783,4918.0,1002,653,-7.267247,-35.88784,1.1523563,2019-05-13 05:22:52,386660,NO_PROBLEM
287,944,1,72976,high_frequency,82,-7.26630,-35.88774,5024.0,1002,680,-7.265687,-35.8877,68.30514,2019-05-13 05:23:22,386659,NO_PROBLEM
298,944,1,72976,high_frequency,85,-7.26180,-35.88736,5526.0,1002,707,-7.261704,-35.8873,12.55985,2019-05-13 05:23:53,386657,NO_PROBLEM
338,944,1,72976,high_frequency,89,-7.25757,-35.88712,5998.0,1002,791,-7.257615,-35.88711,5.1239076,2019-05-13 05:25:55,386656,NO_PROBLEM
378,944,1,72976,high_frequency,94,-7.25295,-35.88723,6511.0,1002,-,-,-,-,2019-05-13 05:27:16,497506,BETWEEN
401,944,1,72976,high_frequency,95,-7.25086,-35.88731,6744.0,1002,907,-7.25092,-35.88729,7.026981,2019-05-13 05:27:57,497505,NO_PROBLEM
443,944,1,72976,high_frequency,99,-7.24893,-35.88736,6959.0,1002,967,-7.248903,-35.88732,5.3368073,2019-05-13 05:29:29,497504,NO_PROBLEM
465,944,1,72976,high_frequency,209,-7.24637,-35.88747,17076.0,1002,1030,-7.246061,-35.88745,34.429985,2019-05-13 05:30:30,491559,NO_PROBLEM
507,944,1,72976,high_frequency,103,-7.24034,-35.88812,7918.0,1002,1130,-7.239697,-35.88815,71.57488,2019-05-13 05:32:02,385793,NO_PROBLEM
520,944,1,72976,high_frequency,105,-7.23617,-35.88859,8385.0,1002,1167,-7.237284,-35.8884,125.63172,2019-05-13 05:32:32,385790,NO_PROBLEM
573,944,1,72976,high_frequency,112,-7.23105,-35.88780,9088.0,1002,1279,-7.230976,-35.88782,8.519057,2019-05-13 05:34:35,1140894,NO_PROBLEM
584,944,1,72976,high_frequency,117,-7.23161,-35.88740,9227.0,1002,-,-,-,-,2019-05-13 05:35:02,1140893,BETWEEN
670,944,1,72976,high_frequency,133,-7.22866,-35.89087,9992.0,1002,1517,-7.228698,-35.89124,41.033257,2019-05-13 05:38:09,491557,NO_PROBLEM
718,944,1,72976,high_frequency,136,-7.22875,-35.89341,10358.0,1002,1642,-7.228809,-35.8934,6.652595,2019-05-13 05:39:41,386653,NO_PROBLEM
763,944,1,72976,high_frequency,140,-7.22643,-35.89263,10633.0,1002,-,-,-,-,2019-05-13 05:41:09,386652,BETWEEN
818,944,1,72976,high_frequency,149,-7.22435,-35.89213,11033.0,1002,-,-,-,-,2019-05-13 05:42:31,385744,BETWEEN
1004,944,1,72976,high_frequency,172,-7.22057,-35.88986,11750.0,1002,-,-,-,-,2019-05-13 05:46:25,386255,BETWEEN
1090,944,1,72976,high_frequency,107,-7.23227,-35.88901,8821.0,1002,-,-,-,-,2019-05-13 05:48:15,386627,BETWEEN
1202,944,1,72976,high_frequency,180,-7.21964,-35.88413,12471.0,1002,2555,-7.21924,-35.8832,111.81814,2019-05-13 05:50:23,386521,NO_PROBLEM
1389,944,1,72976,high_frequency,86,-7.25951,-35.88715,5782.0,1002,-,-,-,-,2019-05-13 05:53:42,491568,BETWEEN
1436,944,1,72976,high_frequency,185,-7.22028,-35.87935,13169.0,1002,2984,-7.221432,-35.87848,160.06067,2019-05-13 05:54:28,385842,NO_PROBLEM
1468,944,1,72976,high_frequency,186,-7.22271,-35.87745,13511.0,1002,3046,-7.222427,-35.87772,43.328472,2019-05-13 05:54:58,385834,NO_PROBLEM
1569,944,1,72976,high_frequency,187,-7.22323,-35.87817,13609.0,1002,3238,-7.223474,-35.87866,60.480232,2019-05-13 05:56:30,386153,NO_PROBLEM
1620,944,1,72976,high_frequency,192,-7.22538,-35.88213,14112.0,1002,-,-,-,-,2019-05-13 05:57:14,386155,BETWEEN
1703,944,1,72976,high_frequency,213,-7.24976,-35.88737,17453.0,1002,-,-,-,-,2019-05-13 05:58:16,491560,BETWEEN
1751,944,1,72976,high_frequency,200,-7.22758,-35.88669,14737.0,1002,-,-,-,-,2019-05-13 05:58:57,386258,BETWEEN
1855,944,1,72976,high_frequency,130,-7.23110,-35.88916,9521.0,1002,3741,-7.2308,-35.88932,37.739895,2019-05-13 06:00:35,386626,NO_PROBLEM
1919,944,1,72976,high_frequency,106,-7.23345,-35.88890,8689.0,1002,3815,-7.232938,-35.88899,57.790947,2019-05-13 06:01:36,385784,NO_PROBLEM
1950,944,1,72976,high_frequency,78,-7.27181,-35.88824,4409.0,1002,-,-,-,-,2019-05-13 06:02:01,385809,BETWEEN
2029,944,1,72976,high_frequency,204,-7.23594,-35.88864,15909.0,1002,4041,-7.23583,-35.88869,13.417473,2019-05-13 06:03:08,386628,NO_PROBLEM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96395,944,15,72976,high_frequency,172,-7.22057,-35.88986,11750.0,1096,-,-,-,-,2019-05-13 21:14:28,386255,BETWEEN
96506,944,15,72976,high_frequency,233,-7.27606,-35.88865,20385.0,1096,-,-,-,-,2019-05-13 21:17:10,385811,BETWEEN
96525,944,15,72976,high_frequency,180,-7.21964,-35.88413,12471.0,1096,178549,-7.220193,-35.88518,131.13908,2019-05-13 21:17:40,386521,NO_PROBLEM
96573,944,15,72976,high_frequency,86,-7.25951,-35.88715,5782.0,1096,-,-,-,-,2019-05-13 21:18:46,491568,BETWEEN
96617,944,15,72976,high_frequency,185,-7.22028,-35.87935,13169.0,1096,178685,-7.220596,-35.87908,46.062675,2019-05-13 21:19:42,385842,NO_PROBLEM
96638,944,15,72976,high_frequency,94,-7.25295,-35.88723,6511.0,1096,-,-,-,-,2019-05-13 21:20:13,497506,BETWEEN
96667,944,15,72976,high_frequency,186,-7.22271,-35.87745,13511.0,1096,178779,-7.222412,-35.87768,41.734085,2019-05-13 21:20:44,385834,NO_PROBLEM
96674,944,15,72976,high_frequency,187,-7.22323,-35.87817,13609.0,1096,-,-,-,-,2019-05-13 21:20:54,386153,BETWEEN
96678,944,15,72976,high_frequency,213,-7.24976,-35.88737,17453.0,1096,-,-,-,-,2019-05-13 21:20:58,491560,BETWEEN
96718,944,15,72976,high_frequency,192,-7.22538,-35.88213,14112.0,1096,178874,-7.225513,-35.88289,85.131454,2019-05-13 21:21:46,386155,NO_PROBLEM
96797,944,15,72976,high_frequency,200,-7.22758,-35.88669,14737.0,1096,179055,-7.227872,-35.8876,105.50377,2019-05-13 21:24:19,386258,NO_PROBLEM
96849,944,15,72976,high_frequency,130,-7.23110,-35.88916,9521.0,1096,179186,-7.230787,-35.88924,35.90539,2019-05-13 21:25:50,386626,NO_PROBLEM
96903,944,15,72976,high_frequency,106,-7.23345,-35.88890,8689.0,1096,179229,-7.234061,-35.88882,68.51083,2019-05-13 21:26:51,385784,NO_PROBLEM
96927,944,15,72976,high_frequency,105,-7.23617,-35.88859,8385.0,1096,-,-,-,-,2019-05-13 21:27:22,385790,BETWEEN
96928,944,15,72976,high_frequency,204,-7.23594,-35.88864,15909.0,1096,179271,-7.235957,-35.88862,2.905262,2019-05-13 21:27:22,386628,NO_PROBLEM
96937,944,15,72976,high_frequency,237,-7.28547,-35.88956,21436.0,1096,-,-,-,-,2019-05-13 21:27:37,386206,BETWEEN
96954,944,15,72976,high_frequency,104,-7.23876,-35.88830,8095.0,1096,179313,-7.23923,-35.88826,52.447548,2019-05-13 21:27:53,385788,NO_PROBLEM
96962,944,15,72976,high_frequency,205,-7.23876,-35.88833,16224.0,1096,-,-,-,-,2019-05-13 21:28:00,491277,BETWEEN
96983,944,15,72976,high_frequency,206,-7.24038,-35.88814,16406.0,1096,179355,-7.241027,-35.88805,72.62487,2019-05-13 21:28:23,386630,NO_PROBLEM
96997,944,15,72976,high_frequency,102,-7.24304,-35.88780,7616.0,1096,179396,-7.24303,-35.88783,3.4910493,2019-05-13 21:28:53,491555,NO_PROBLEM
97009,944,15,72976,high_frequency,207,-7.24312,-35.88782,16712.0,1096,-,-,-,-,2019-05-13 21:29:13,386631,BETWEEN
97019,944,15,72976,high_frequency,208,-7.24372,-35.88777,16779.0,1096,179438,-7.244688,-35.88764,108.587715,2019-05-13 21:29:24,491558,NO_PROBLEM
97033,944,15,72976,high_frequency,101,-7.24638,-35.88743,7242.0,1096,179481,-7.246846,-35.88743,51.816837,2019-05-13 21:29:55,386594,NO_PROBLEM
97237,944,15,72976,high_frequency,89,-7.25757,-35.88712,5998.0,1096,-,-,-,-,2019-05-13 21:33:49,386656,BETWEEN
97271,944,15,72976,high_frequency,82,-7.26630,-35.88774,5024.0,1096,179833,-7.266075,-35.88775,25.043161,2019-05-13 21:35:01,386659,NO_PROBLEM
97291,944,15,72976,high_frequency,81,-7.26725,-35.88783,4918.0,1096,179878,-7.267232,-35.88784,2.285319,2019-05-13 21:35:31,386660,NO_PROBLEM
97305,944,15,72976,high_frequency,79,-7.27052,-35.88815,4552.0,1096,179923,-7.270063,-35.8881,51.11448,2019-05-13 21:36:02,386606,NO_PROBLEM
97312,944,15,72976,high_frequency,78,-7.27181,-35.88824,4409.0,1096,-,-,-,-,2019-05-13 21:36:11,385809,BETWEEN
97360,944,15,72976,high_frequency,62,-7.28514,-35.88951,2903.0,1096,180059,-7.28361,-35.88935,171.04109,2019-05-13 21:37:34,385813,NO_PROBLEM
97393,944,15,72976,high_frequency,240,-7.28793,-35.88991,21713.0,1096,180152,-7.288075,-35.88992,16.160946,2019-05-13 21:38:35,386661,NO_PROBLEM

In [11]:
bus_trips_clean = bus_trips.filter(['route','busCode','tripNum','stopPointId','gps_datetime'])

In [12]:
bus_trips_clean.head()

     route  busCode  tripNum  stopPointId        gps_datetime
5900  004A     3005        1       385835 2019-05-13 06:45:24
5962  004A     3005        1       386394 2019-05-13 06:45:55
6129  004A     3005        1       386129 2019-05-13 06:47:47
6244  004A     3005        1       386131 2019-05-13 06:48:59
6486  004A     3005        1       385833 2019-05-13 06:51:35

In [25]:
bus_trips_clean[bus_trips_clean.route == "944"]

      route  busCode  tripNum  stopPointId        gps_datetime
278     944     1002        1       386660 2019-05-13 05:22:52
287     944     1002        1       386659 2019-05-13 05:23:22
298     944     1002        1       386657 2019-05-13 05:23:53
338     944     1002        1       386656 2019-05-13 05:25:55
378     944     1002        1       497506 2019-05-13 05:27:16
401     944     1002        1       497505 2019-05-13 05:27:57
443     944     1002        1       497504 2019-05-13 05:29:29
465     944     1002        1       491559 2019-05-13 05:30:30
507     944     1002        1       385793 2019-05-13 05:32:02
520     944     1002        1       385790 2019-05-13 05:32:32
573     944     1002        1      1140894 2019-05-13 05:34:35
584     944     1002        1      1140893 2019-05-13 05:35:02
670     944     1002        1       491557 2019-05-13 05:38:09
718     944     1002        1       386653 2019-05-13 05:39:41
763     944     1002        1       386652 2019-05-13 05:41:09
818     944     1002        1       385744 2019-05-13 05:42:31
1004    944     1002        1       386255 2019-05-13 05:46:25
1090    944     1002        1       386627 2019-05-13 05:48:15
1202    944     1002        1       386521 2019-05-13 05:50:23
1389    944     1002        1       491568 2019-05-13 05:53:42
1436    944     1002        1       385842 2019-05-13 05:54:28
1468    944     1002        1       385834 2019-05-13 05:54:58
1569    944     1002        1       386153 2019-05-13 05:56:30
1620    944     1002        1       386155 2019-05-13 05:57:14
1703    944     1002        1       491560 2019-05-13 05:58:16
1751    944     1002        1       386258 2019-05-13 05:58:57
1855    944     1002        1       386626 2019-05-13 06:00:35
1919    944     1002        1       385784 2019-05-13 06:01:36
1950    944     1002        1       385809 2019-05-13 06:02:01
2029    944     1002        1       386628 2019-05-13 06:03:08
...     ...      ...      ...          ...                 ...
96395   944     1096       15       386255 2019-05-13 21:14:28
96506   944     1096       15       385811 2019-05-13 21:17:10
96525   944     1096       15       386521 2019-05-13 21:17:40
96573   944     1096       15       491568 2019-05-13 21:18:46
96617   944     1096       15       385842 2019-05-13 21:19:42
96638   944     1096       15       497506 2019-05-13 21:20:13
96667   944     1096       15       385834 2019-05-13 21:20:44
96674   944     1096       15       386153 2019-05-13 21:20:54
96678   944     1096       15       491560 2019-05-13 21:20:58
96718   944     1096       15       386155 2019-05-13 21:21:46
96797   944     1096       15       386258 2019-05-13 21:24:19
96849   944     1096       15       386626 2019-05-13 21:25:50
96903   944     1096       15       385784 2019-05-13 21:26:51
96927   944     1096       15       385790 2019-05-13 21:27:22
96928   944     1096       15       386628 2019-05-13 21:27:22
96937   944     1096       15       386206 2019-05-13 21:27:37
96954   944     1096       15       385788 2019-05-13 21:27:53
96962   944     1096       15       491277 2019-05-13 21:28:00
96983   944     1096       15       386630 2019-05-13 21:28:23
96997   944     1096       15       491555 2019-05-13 21:28:53
97009   944     1096       15       386631 2019-05-13 21:29:13
97019   944     1096       15       491558 2019-05-13 21:29:24
97033   944     1096       15       386594 2019-05-13 21:29:55
97237   944     1096       15       386656 2019-05-13 21:33:49
97271   944     1096       15       386659 2019-05-13 21:35:01
97291   944     1096       15       386660 2019-05-13 21:35:31
97305   944     1096       15       386606 2019-05-13 21:36:02
97312   944     1096       15       385809 2019-05-13 21:36:11
97360   944     1096       15       385813 2019-05-13 21:37:34
97393   944     1096       15       386661 2019-05-13 21:38:35

[3529 rows x 5 columns]

In [13]:
bus_trips_clean.dtypes

route                   object
busCode                  int64
tripNum                  int64
stopPointId              int64
gps_datetime    datetime64[ns]
dtype: object

In [14]:
otp_suggestions_bus_legs.dtypes

otp_date                   datetime64[ns]
otp_user_trip_id                  float64
otp_itinerary_id                    int64
otp_leg_id                          int64
otp_start_time             datetime64[ns]
otp_end_time               datetime64[ns]
otp_mode                           object
otp_route                          object
otp_from_stop_id                  float64
otp_to_stop_id                    float64
otp_duration_mins                 float64
otp_from_parent_station           float64
otp_to_parent_station             float64
dtype: object

## Identify Possible Matches between OTP Itineraries and Bus Trips Observed Data

In [35]:
scheduled_itin_observed_o = otp_suggestions_bus_legs.merge(bus_trips_clean.add_prefix('bt_'),
                                left_on=['otp_route','otp_from_stop_id'],
                                right_on=['bt_route','bt_stopPointId'],
                                how='inner') \
                                .drop(['bt_route'], axis=1) \
                                .rename(index=str, columns={'bt_gps_datetime':'bt_start_time',
                                                            'bt_tripNum':'bt_trip_num',
                                                            'bt_busCode':'bt_bus_code'}) \
                                .assign(sched_obs_start_timediff = 
                                        lambda x: np.absolute(x['bt_start_time'] - x['otp_start_time']))

In [36]:
scheduled_itin_observed_o[scheduled_itin_observed_o.otp_route == "944"]["otp_start_time","otp_route","otp_from_stop_id",
                                                                           "otp_from_stop_id", "bt_start_time"]

SyntaxError: invalid syntax (<ipython-input-36-a32aaca164e2>, line 1)

In [16]:
scheduled_itin_observed_od = scheduled_itin_observed_o.merge(bus_trips_clean.add_prefix('bt_'),
                                left_on=['otp_route','bt_bus_code','bt_trip_num','otp_to_stop_id'],
                                right_on=['bt_route','bt_busCode','bt_tripNum','bt_stopPointId'],
                                how='inner') \
                                .drop(['bt_route','bt_stopPointId'], axis=1) \
                                .rename(index=str, columns={'bt_gps_datetime':'bt_end_time'}) \
                                .assign(sched_obs_end_timediff = 
                                        lambda x: np.absolute(x['bt_end_time'] - x['otp_end_time'])) \
                                .sort_values(['otp_user_trip_id','otp_itinerary_id','otp_leg_id','sched_obs_start_timediff','sched_obs_end_timediff'])

In [17]:
len(scheduled_itin_observed_od)

26845

In [18]:
scheduled_itin_observed_od['bt_duration_mins'] = (scheduled_itin_observed_od['bt_end_time'] - scheduled_itin_observed_od['bt_start_time'])/pd.Timedelta(minutes=1)
scheduled_itin_observed_od = scheduled_itin_observed_od[scheduled_itin_observed_od['bt_duration_mins'] > 0]

In [19]:
len(scheduled_itin_observed_od)

22121

In [20]:
scheduled_itin_observed_od_full = pd.concat([scheduled_itin_observed_od,otp_suggestions_walk_legs], sort=False)

In [23]:
bus_trips_clean[(bus_trips['route'] == '944') & (bus_trips['stopPointId'] == 491551)].sort_values(['gps_datetime'])

      route  busCode  tripNum  stopPointId        gps_datetime
4266    944     1002        2       491551 2019-05-13 06:29:21
6146    944     1052        2       491551 2019-05-13 06:47:57
8084    944     1096        2       491551 2019-05-13 07:06:16
12536   944     1002        3       491551 2019-05-13 07:44:09
14182   944     1051        2       491551 2019-05-13 07:56:49
15108   944     1052        3       491551 2019-05-13 08:04:18
16849   944     1096        3       491551 2019-05-13 08:18:15
21922   944     1002        4       491551 2019-05-13 08:54:42
24607   944     1096        5       491551 2019-05-13 09:34:54
28785   944     1002        5       491551 2019-05-13 10:08:54
29965   944     1051        3       491551 2019-05-13 10:19:02
33304   944     1096        6       491551 2019-05-13 10:45:12
38165   944     1002        6       491551 2019-05-13 11:25:35
38200   944     1051        4       491551 2019-05-13 11:25:48
39483   944     1051        5       491551 2019-05-13 11:36:10
41848   944     1096        7       491551 2019-05-13 11:57:15
44940   944     1052        6       491551 2019-05-13 12:22:26
46834   944     1002        7       491551 2019-05-13 12:38:05
48354   944     1051        6       491551 2019-05-13 12:50:51
49345   944     1096        8       491551 2019-05-13 13:00:06
53886   944     1052        7       491551 2019-05-13 13:40:01
54793   944     1002        8       491551 2019-05-13 13:47:41
55289   944     1002        9       491551 2019-05-13 13:51:44
61747   944     1052        8       491551 2019-05-13 14:52:34
63527   944     1002       10       491551 2019-05-13 15:09:42
67991   944     1096        9       491551 2019-05-13 15:51:29
68392   944     1096       10       491551 2019-05-13 15:55:46
69683   944     1052        9       491551 2019-05-13 16:08:39
71853   944     1002       12       491551 2019-05-13 16:28:21
72477   944     1051        8       491551 2019-05-13 16:34:07
72895   944     1051        9       491551 2019-05-13 16:38:11
76450   944     1096       11       491551 2019-05-13 17:11:14
78067   944     1052       10       491551 2019-05-13 17:25:59
79863   944     1002       13       491551 2019-05-13 17:43:07
81030   944     1051       10       491551 2019-05-13 17:54:37
81033   944     1002       14       491551 2019-05-13 17:54:40
84934   944     1096       12       491551 2019-05-13 18:34:03
85097   944     1052       11       491551 2019-05-13 18:35:26
87681   944     1002       15       491551 2019-05-13 18:58:51
88809   944     1051       11       491551 2019-05-13 19:09:40
91534   944     1096       13       491551 2019-05-13 19:44:08
91793   944     1052       13       491551 2019-05-13 19:48:22
93541   944     1051       12       491551 2019-05-13 20:16:21
94862   944     1096       14       491551 2019-05-13 20:38:54
98968   944     1052       15       491551 2019-05-13 22:20:39
99625   944     1051       13       491551 2019-05-13 22:51:30
99683   944     1051       14       491551 2019-05-13 22:55:35

In [ ]:
scheduled_itin_observed_od_full.head() \
                            .sort_values(['otp_user_trip_id','otp_itinerary_id','otp_leg_id'])

In [ ]:
scheduled_itin_observed_od_full_clean = scheduled_itin_observed_od_full \
                            .filter(['otp_user_trip_id','otp_itinerary_id','otp_leg_id','otp_mode','otp_route',
                                     'bt_bus_code','bt_trip_num','otp_from_stop_id','otp_start_time',
                                     'bt_start_time','sched_obs_start_timediff','otp_to_stop_id',
                                     'otp_end_time','bt_end_time','sched_obs_end_timediff','otp_duration_mins','minimun_obs_start_time']) \
                            .sort_values(['otp_user_trip_id','otp_itinerary_id','otp_leg_id'])

In [ ]:
scheduled_itin_observed_od_full_clean

In [ ]:
scheduled_itin_observed_od_full_clean \
                        .groupby(['otp_itinerary_id', 'otp_leg_id']) \
                        .apply(lambda x: x.sort_values(["sched_obs_start_timediff"]))

In [ ]:
# Filtering out itineraries which lost bus legs along the processing
original_suggested_itins_num_legs = otp_suggestions.groupby(['otp_user_trip_id','otp_itinerary_id']) \
                                    .agg({'otp_leg_id': lambda x: len(x)}) \
                                    .reset_index() \
                                    .rename(index=str, columns={'otp_leg_id':'num_legs'})

curr_matched_itins_num_legs = scheduled_itin_observed_od_full_clean.groupby(['otp_user_trip_id','otp_itinerary_id']) \
                                    .agg({'otp_leg_id': lambda x: len(np.unique(x))}) \
                                    .reset_index() \
                                    .rename(index=str, columns={'otp_leg_id':'num_legs'})

complete_matched_itins = original_suggested_itins_num_legs.merge(curr_matched_itins_num_legs, how='inner')

all_complete_vehicle_legs_options = scheduled_itin_observed_od_full_clean.merge(complete_matched_itins.drop('num_legs', axis=1), how='inner')

In [ ]:
def is_new_itinerary(prev_trip_id,curr_trip_id,prev_itin_id,curr_itin_id):
    return ((prev_trip_id != curr_trip_id) | (prev_itin_id != curr_itin_id))

def choose_leg_matches(leg_matches_groups):
        colnames = leg_matches_groups.obj.columns.values
        chosen_leg_matches = pd.DataFrame(columns = colnames)
        prev_trip_id = -1
        prev_itin_id = -1
        prev_leg_mode = ""
        prev_leg_end_time = pd.NaT
        num_groups_not_survived = 0
        new_itinerary = False

        for name, group in leg_matches_groups:
            
                #print
                #print "Name:", name
                #print "Group:"
                #print group
                #print
                
                curr_trip_id = group['otp_user_trip_id'].iloc[0]
                curr_itin_id = group['otp_itinerary_id'].iloc[0]
                curr_leg_id = group['otp_leg_id'].iloc[0]
                curr_leg_mode = group['otp_mode'].iloc[0]
                
                new_itinerary = is_new_itinerary(prev_trip_id,curr_trip_id,prev_itin_id,curr_itin_id)
                if new_itinerary:
                    prev_leg_end_time = group['otp_start_time'].dt.floor('d').iloc[0]

                #if (prev_group_id == ()):
                #        prev_leg_end_time = group['bt_start_time'].dt.floor('d')[0]

                #print
                #print "Previous itinerary id:", prev_itin_id
                #print "Previous leg mode:", prev_leg_mode
                #print "Previous leg end time:", prev_leg_end_time
                #print "Current leg id:", curr_leg_id
                #print "Current leg mode:", curr_leg_mode
                #print
                #print "Original Group"
                #print group.filter(['otp_start_time','bt_start_time','bt_end_time'])
                
                if (curr_leg_mode == 'WALK'):
                    #print "Walking duration:", filtered_group['otp_duration_mins']
                    filtered_group = group.reset_index()
                    if new_itinerary: #first leg is a WALK leg
                        filtered_group.loc[0,'bt_end_time'] = prev_leg_end_time
                    else:
                        filtered_group.loc[0,'bt_start_time'] = prev_leg_end_time
                        filtered_group.loc[0,'bt_end_time'] = prev_leg_end_time + \
                            pd.Timedelta(minutes=np.rint(filtered_group['otp_duration_mins'].iloc[0]))
                    #print "Filtered Group"
                    #print filtered_group
                else:
                    filtered_group = group[group['bt_start_time'] > prev_leg_end_time]
                
                #print
                #print "Filtered Group"
                #print filtered_group.filter(['otp_start_time','bt_start_time','bt_end_time'])

                if (len(filtered_group) == 0):
                        #print "Group did not survive! =("
                        #print
                        #print "Previous itinerary id:", prev_itin_id
                        #print "Previous leg mode:", prev_leg_mode
                        #print "Previous leg end time:", prev_leg_end_time
                        #print "Current leg id:", curr_leg_id
                        #print "Current leg mode:", curr_leg_mode
                        #print
                        #print "Original Group"
                        #print group#.filter(['otp_start_time','bt_start_time','bt_end_time'])
                        num_groups_not_survived += 1
                        continue

                chosen_leg_match = filtered_group.sort_values('bt_start_time').iloc[0]
                
                if ((curr_leg_id == 2) & 
                    ((curr_leg_mode == 'BUS') & (prev_leg_mode == 'WALK'))):
                        #Update previous walk start/end_times
                        #print
                        #print "Chosen Leg Matches"
                        #print chosen_leg_matches.iloc[-1]
                        #print
                        chosen_leg_matches.iloc[-1,chosen_leg_matches.columns.get_loc('bt_start_time')] = chosen_leg_match['bt_start_time'] - \
                            pd.Timedelta(minutes=np.rint(chosen_leg_matches.iloc[-1].otp_duration_mins))
                        chosen_leg_matches.iloc[-1,chosen_leg_matches.columns.get_loc('bt_end_time')] = chosen_leg_match['bt_start_time']
                #print "Chosen Leg"
                #print chosen_leg_match

                chosen_leg_matches = chosen_leg_matches.append(chosen_leg_match)

                #Update variables
                #prev_group_id = name
                prev_trip_id = curr_trip_id
                prev_itin_id = curr_itin_id
                prev_leg_mode = curr_leg_mode
                prev_leg_end_time = chosen_leg_match['bt_end_time']

        #print "Number of groups which did not survive:", num_groups_not_survived
        return chosen_leg_matches.filter(colnames)

In [ ]:
# Choose best actual leg matches (based on feasibility and start time)
feasible_legs = choose_leg_matches(scheduled_itin_observed_od_full_clean.groupby(['otp_user_trip_id','otp_itinerary_id','otp_leg_id']))

if len(feasible_legs) == 0:
    print "No matches left after matching and selecting feasible bus legs."
    print "Skipping next steps..."
    exit(0)

# Filtering out itineraries which lost bus legs after feasible legs choice processing
feasible_itins_num_legs = feasible_legs.groupby(['otp_user_trip_id','otp_itinerary_id']) \
                                    .agg({'otp_leg_id': lambda x: len(x)}) \
                                    .reset_index() \
                                    .rename(index=str, columns={'otp_leg_id':'num_legs'})

feasible_complete_itins = feasible_itins_num_legs.merge(original_suggested_itins_num_legs,how='inner')

feasible_complete_itins_legs = feasible_legs.merge(feasible_complete_itins.drop('num_legs', axis=1),how='inner')

In [ ]:
def add_stops_data_to_legs(itineraries_legs,stops_locs):
    itineraries_legs_stops = itineraries_legs.merge(stops_locs, left_on='otp_from_stop_id', right_on='stop_id', how='left') \
                                                                                .drop('stop_id', axis=1) \
                                                                                .rename(index=str, columns={'stop_lat':'from_stop_lat','stop_lon':'from_stop_lon'}) \
                                                                                .merge(stops_locations, left_on='otp_to_stop_id', right_on='stop_id', how='left') \
                                                                                .drop('stop_id', axis=1) \
                                                                                .rename(index=str, columns={'stop_lat':'to_stop_lat','stop_lon':'to_stop_lon'}) 
    return itineraries_legs_stops

In [ ]:
stops_locations = stops_df[['stop_id','stop_lat','stop_lon']]
itineraries_legs = add_stops_data_to_legs(feasible_complete_itins_legs,stops_locations)

In [ ]:
feasible_complete_itins_legs